### ISSUE TITLE
Errors in some of the simulations

### ISSUE THREAD

**Issue by robfairh** [arfc/pride#114]
Learning how to set up a scenario in Temoa I ran into some things.

The following scenarios have output related issues:
* 01_uiuc
* 05_uiuc
* 06_uiuc

The following scenarios have input related issues:
* 03_uiuc_mga

Here are the log files: 
* [01_uiuc-err.txt](https://github.com/arfc/pride/files/5661456/01_uiuc-err.txt)
* [05_uiuc-err.txt](https://github.com/arfc/pride/files/5661458/05_uiuc-err.txt)
* [06_uiuc-err.txt](https://github.com/arfc/pride/files/5661459/06_uiuc-err.txt)
* [03_uiuc_mga-err.txt](https://github.com/arfc/pride/files/5661457/03_uiuc_mga-err.txt)

I have two questions:

I am not sure about the output related issues.
From my little understanding of Temoa, it seems like those figures are not possible for those input files.
1 - Does it mean that the solution would require a different snakemake?

About the input related issue, I am assuming that that file was not updated.
2- Is this correct?
I could try bringing it up-to-date.

This issue can be closed when:
- [ ] @samgdotson has answered the two questions in this issue.
- [x] A strategy to solve the simulation issues.
- [ ] The strategy has been implemented.

**Comment by samgdotson** [comment]
1. In the README I mentioned that MGA can't be conducted with snakemake (at the moment). 
2. Snakemake runs all of the scenarios on my end. But scenario 1 does not have a solution, apparently. I'm not sure why that is happening now, it was not previously, but it doesn't need to be fixed rn because the later scenarios still run properly. 
3. Scenario 5 and 6 still run for me and produce the plots.
4. If you want to run MGA, use the  jupyter notebook ``mga_analysis``

**Comment by samgdotson** [comment]
Numbered scenarios will be deprecated once a complete model of UIUC has been developed.
