### ISSUE TITLE
Transportation sector output analysis

### ISSUE THREAD

**Issue by robfairh** [arfc/pride#123]
This is figure 'scenario09_vcl_generation' of the updated model from PR #122.

![scenario09_vcl_generation](https://user-images.githubusercontent.com/43791150/102606361-64fee380-4105-11eb-929f-b2e9a08cf633.png)

It seems like in the very first year, the vehicle fleet uses three different fuels.
In the next few year, it uses only one fuel each year and alternates between different fuels between different years.
@samgdotson what do you think about it? Is this something reasonable?

**Comment by robfairh** [comment]
I think there might be a bug somewhere.
These are the most recent outputs:

![scenario09_all_emissions_ewaste](https://user-images.githubusercontent.com/43791150/102632298-ab683880-412d-11eb-9a4f-0c3f6987b99f.png)

![scenario09_vcl_generation](https://user-images.githubusercontent.com/43791150/102632311-b02cec80-412d-11eb-9482-e98d059834c0.png)

While the first image shows that there is some waste produced by ELCVCL, the second one doesn't show any generation of kGGE from electricity.

@samgdotson thoughts?

**Comment by samgdotson** [comment]
@robfairh 
1.Yes, the behavior of switching between vehicle technology is not at all realistic. The reason this is happening is because we haven't specified a FixedCost for each vehicle type. In a sense, the model is ''punished'' for not using a technology it has already deployed. 
2. If electric vehicles are never used, then there isn't any waste produced. The EWASTE graph shows all technologies that *could* contribute to the waste. This is maybe a dumb behavior, but that's what ``data_parser`` is doing.
